apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        
        envFrom:
        - secretRef:
            name: nginx-secret
            
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf 
    
        - name: nginx-data-volume
          mountPath: /var/log/nginx
          
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
          
      - name: nginx-data-volume
        persistentVolumeClaim:
          claimName: pvc-data